apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-keycloak
  labels:
    app: frontend-keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-keycloak
  template:
    metadata:
      labels:
        app: frontend-keycloak
    spec:
      containers:
      - name: frontend-keycloak        
        image: ghcr.io/kyleee0522/vue_crud_security_keycloak:v1
        imagePullPolicy: Always
        env:
          - name: BACKEND_API_URL
            value: "backend-keycloak:80" 
        ports:
        - containerPort: 80
